# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'left_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3

class Left_panel(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName("Tag")
        DockWidget.resize(200, 800)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(self.dockWidgetContents)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.button_search = QtWidgets.QPushButton(self.dockWidgetContents)
        self.button_search.setObjectName("button_search")
        self.horizontalLayout.addWidget(self.button_search)
        self.button_addtag = QtWidgets.QPushButton(self.dockWidgetContents)
        self.button_addtag.setObjectName("button_addtag")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)
        
        

    def retranslateUi(self, DockWidget):
        _translate = QtCore.QCoreApplication.translate
        DockWidget.setWindowTitle(_translate("DockWidget", "DockWidget"))
        self.button_search.setText(_translate("DockWidget", "搜索TAG"))
        self.button_addtag.setText(_translate("DockWidget", "添加TAG"))

    def create_tag(self):
        conn = sqlite3.connect("tag.db")
        cur = conn.cursor()
        sql_text = '''CREATE TABLE tag 
                   (路径 TEXT, 
                    TAG TEXT);'''
        cur.execute(sql_text)
        conn.commit()
        cur.close()
        conn.close()

    def add_tag(self, path, tag):
        conn = sqlite3.connect("tag.db")
        cur = conn.cursor()
        data = (path, tag)
        sql_text = "INSERT INTO tag VALUES"+str(data)
        cur.execute(sql_text)
        conn.commit()
        cur.close()
        conn.close()

    def search_through_tag(self, tag):
        conn = sqlite3.connect("tag.db")
        cur = conn.cursor()
        sql_text = "SELECT * FROM tag WHERE TAG="+tag
        cur.execute(sql_text)
        return cur.fetchall()



